export const db = {
  users: [
    { id: 1, name: 'Alice (Creator)', email: 'creator@lt.com', password: 'password', role: 'Creator', performanceScore: 80 },
    { id: 2, name: 'Azad (HOD)', email: 'azad@lt.com', password: 'password', role: 'HOD', performanceScore: 85 },
    { id: 3, name: 'Anurag (HOD)', email: 'anurag@lt.com', password: 'password', role: 'HOD', performanceScore: 88 },
    { id: 4, name: 'Charlie (Member)', email: 'member1@lt.com', password: 'password', role: 'Member', performanceScore: 85 },
    { id: 5, name: 'Dana (Member)', email: 'member2@lt.com', password: 'password', role: 'Member', performanceScore: 90 },
  ],
  projects: [] as any[],
  teams: [] as any[],
  tasks: [] as any[],
  milestones: [] as any[],
  experienceHistory: [] as any[],
  activityFeed: [] as any[],
  notifications: [] as any[],
  tenderOutcomes: [] as any[],
  performanceReviews: [] as any[],
  employeeExperiences: [] as any[],
  leadershipHistory: [] as any[],
  categories: [
    { name: 'Roads', color: '#3b82f6' },
    { name: 'Runways', color: '#10b981' },
    { name: 'Elevated Corridors', color: '#8b5cf6' },
    { name: 'Railways', color: '#f59e0b' },
    { name: 'Bridges', color: '#ef4444' },
    { name: 'Buildings', color: '#ec4899' },
  ],
  projectIdCounter: 1,
  activityIdCounter: 1,
  notificationIdCounter: 1,
  teamIdCounter: 1,
  taskIdCounter: 1,
  performanceReviewIdCounter: 1,
  userIdCounter: 6,
  employeeExperienceIdCounter: 1,
  leadershipHistoryIdCounter: 1,
};
